### ISSUE TITLE
3scale application apply is not idempotent

### ISSUE THREAD

**Issue by nmasse-itix** [3scale/3scale_toolbox#175]
# current behavior

```sh
$ bundle exec 3scale application apply nmasse-redhat 1234567 --account=2445582535751 --name=test --description=test --plan=basic --service=api --suspend
Applied application id: 1409618464759; Suspended
$ bundle exec 3scale application apply nmasse-redhat 1234567 --account=2445582535751 --name=test --description=test --plan=basic --service=api --suspend
Error: Application has not been suspended. Errors: {"state"=>["cannot transition via \"suspend\""]}
$ bundle exec 3scale application apply nmasse-redhat 1234567 --account=2445582535751 --name=test --description=test --plan=basic --service=api --resume
Applied application id: 1409618464759; Resumed
$ bundle exec 3scale application apply nmasse-redhat 1234567 --account=2445582535751 --name=test --description=test --plan=basic --service=api --resume
Error: Application has not been resumed. Errors: {"state"=>["cannot transition via \"resume\""]}
```

# expected behavior

```sh
$ bundle exec 3scale application apply nmasse-redhat 1234567 --account=2445582535751 --name=test --description=test --plan=basic --service=api --state=suspended
Applied application id: 1409618464759; Suspended
$ bundle exec 3scale application apply nmasse-redhat 1234567 --account=2445582535751 --name=test --description=test --plan=basic --service=api --state=suspended
Applied application id: 1409618464759; Suspended
$ bundle exec 3scale application apply nmasse-redhat 1234567 --account=2445582535751 --name=test --description=test --plan=basic --service=api --state=active
Applied application id: 1409618464759; Resumed
$ bundle exec 3scale application apply nmasse-redhat 1234567 --account=2445582535751 --name=test --description=test --plan=basic --service=api --state=active
Applied application id: 1409618464759; Resumed
```

**Comment by eguzki** [comment]
Fixed https://github.com/3scale/3scale_toolbox/pull/172

**Comment by nmasse-itix** [comment]
Mental connection between the developer team and QE. 😄

**Comment by nmasse-itix** [comment]
Almost, in fact. 

I tested the master but the problem still exists. In fact, your PR is about making the application-plan command idempotent and this issue is about the **application** command.

**Comment by eguzki** [comment]
ops sorry, you are totally right. Will fix it
